title: brower.xyz
email: ejbrower4@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Jack Brower's portfolio.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.brower.xyz/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jackbrower

# Build settings
theme: jekyll-shell-theme
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - index.md
  - projects.md
  - resume.md
  - contact.md

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
